src/blog/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from accounts import views as account_views

from rest_framework_jwt.views import obtain_jwt_token

from accounts.views import (login_view, register_view, logout_view, change_password, create_profile)

from django.contrib.auth.views import (
    password_reset, 
    password_reset_done,
    password_reset_confirm, 
    password_reset_complete,
)

from posts.feeds import ArchiveFeed, AtomSiteNewsFeed

urlpatterns = [
    
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^admin/', admin.site.urls),
    url(r'^comments/', include("comments.urls", namespace='comments')),
    url(r'^profile/', account_views.profile, name='profile'),
    url(r'^register/', register_view, name='register'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^change-password/', change_password, name='change-password'),
    url(r'^create-profile/', create_profile, name='create_profile'),
    url(r'^', include("posts.urls", namespace='posts')),
    url(r'^api/posts/', include("posts.api.urls", namespace='posts-api')),
    url(r'^api/comments/', include("comments.api.urls", namespace='comments-api')),
    url(r'^api/users/', include("accounts.api.urls", namespace='users-api')),

    url(r'^newsletter/', include("newsletters.urls", namespace='newsletters')),

    url(r'^api/auth/token/', obtain_jwt_token),
    # url(r'^api/auth/token/', obtain_jwt_token),
    #url(r'^posts/$', "<appname>.views.<function_name>"),

    url(r'^account/reset-password/', password_reset,  name='reset_password'),
    url(r'^account/password-reset/done/$', password_reset_done, name='password_reset_done'),
    url(r'^account/password-reset/confirm/(?P<uidb64>[\w-]+)/(?P<token>[\w-]+)/$', password_reset_confirm, name='password_reset_confirm'),
    url(r'^account/password-reset/complete/$', password_reset_complete, name='password_reset_complete'),


    url(r'^oauth/', include("social_django.urls", namespace='social')),

    #url(r'^rss/', include("rss.urls", namespace='rss')),

    url(r'^feed/archive/$', ArchiveFeed(), name='archive-feed'),
    #url(r'^feed/atom/$', AtomSiteNewsFeed()),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/newsletters/urls.py
from django.conf.urls import url

from .views import (
	newsletter_signup,
	newsletter_unsubscribe,
	)

urlpatterns = [
	url(r'^sign_up/$', newsletter_signup, name='newsletter_signup'),
    url(r'^unsubscribe/$', newsletter_unsubscribe, name='newsletter_unsubscribe'),
]

src/rss/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^feeds/', views.rest_feeds, name='rest-feeds'),
	url(r'^feeds/(?P<pk>[0-9]+)/$', views.rest_feeds_detail, name='rest-feeds-detail'),
	url(r'^items/', views.rest_items, name='rest-items')
]

src/newsletters/models.py
from django.db import models

# Create your models here.
class NewsletterUser(models.Model):
	email = models.EmailField()
	date_added = models.DateTimeField(auto_now_add=True)
	
	def __str__(self):
		return self.email
		

src/newsletters/forms.py
from django import forms
from .models import NewsletterUser

class NewsletterUserSignUpForm(forms.ModelForm):
	email = forms.EmailField(label='', widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'your@email.com'}))
	class Meta:
		model = NewsletterUser
		fields = [
            "email",
        ]

		def clean_email(self):
			email = self.cleaned_data.get('email')

			return email

src/newsletters/views.py
from django.conf import settings
from django.contrib import messages
from django.shortcuts import render
from django.core.mail import send_mail, EmailMultiAlternatives
from django.template.loader import get_template

from .models import NewsletterUser
from .forms import NewsletterUserSignUpForm
# Create your views here.

def newsletter_signup(request):
	form = NewsletterUserSignUpForm(request.POST or None)

	if form.is_valid():
		instance = form.save(commit=False)

		if NewsletterUser.objects.filter(email=instance.email).exists():
			messages.warning(request, "Sorry! this email already exist!", "alert alert-warning alert-dismissible")
		else:
			instance.save()
			messages.success(request, "Your email has been submited.", "alert alert-success alert-dismissible")

			subject = "Thank you for joing our Newsletter"
			from_email = settings.EMAIL_HOST_USER
			to_email = [instance.email]
			#signup_message = """Welcome to our bloger site Newsletter. If you would like to unsubscribe visit http://127.0.0.1:8000/newsletter/unsubscribe"""
			#send_mail(subject=subject, from_email=from_email, recipient_list=to_email, message=signup_message, fail_silently=False)

			with open(settings.BASE_DIR + "/templates/newsletters/sign_up_email.txt") as f:
				signup_message = f.read()
			message = EmailMultiAlternatives(subject=subject, body=signup_message, from_email=from_email, to=to_email)
			html_template = get_template("newsletters/sign_up_email.html").render()
			message.attach_alternative(html_template, "text/html")
			message.send()

	context = {
		'form': form,
	}

	return render(request, "newsletters/sign_up.html", context)


def newsletter_unsubscribe(request):
	form = NewsletterUserSignUpForm(request.POST or None)

	if form.is_valid():
		instance = form.save(commit=False)

		if NewsletterUser.objects.filter(email=instance.email).exists():
			NewsletterUser.objects.filter(email=instance.email).delete()
			messages.success(request, "Your email has been removed.", "alert alert-success alert-dismissible")

			subject = "You have been unsubscribe"
			from_email = settings.EMAIL_HOST_USER
			to_email = [instance.email]
			#signup_message = """Sorry to see you go, let us know if there is an issue with our service"""
			#send_mail(subject=subject, from_email=from_email, recipient_list=to_email, message=signup_message, fail_silently=False)

			with open(settings.BASE_DIR + "/templates/newsletters/unsubscribe_email.txt") as f:
				signup_message = f.read()
			message = EmailMultiAlternatives(subject=subject, body=signup_message, from_email=from_email, to=to_email)
			html_template = get_template("newsletters/unsubscribe_email.html").render()
			message.attach_alternative(html_template, "text/html")
			message.send()
		else:
			messages.warning(request, "Sorry! but we did not found your email address", "alert alert-warning alert-dismissible")

	context = {
		'form': form,
	}

	return render(request, "newsletters/unsubscribe.html", context)

src/templates/newsletters/sign_up.html
{% extends "base.html" %}

{% block head_title %}
    Sign up Newsletter | {{ block.super }}
{% endblock head_title %}

{% block content %}
<br>
<div class="container">
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="post">
                <div class="topwrap">
                    <div class="subscribe-section bg-with-black">
                        <div class="container">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="subscribe-head">
                                        <h1>Newsletter</h1>
                                        <h2>DO you need more tips?</h2>
                                        <p>Than Subscribe For Free And get the latest tips.</p>
                                        <a href="#modal-id-2" class="btn"><i class="fa fa-sign-in" aria-hidden="true"></i>&nbsp;Sign up Here</a>
                                        <small><em></em></small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="light-modal" id="modal-id-2" role="dialog" aria-labelledby="light-modal-label" aria-hidden="false">
        <div class="light-modal-content  animated zoomInUp">
            <!-- light modal header -->
            <div class="light-modal-header">
                <h3 class="light-modal-heading"><i class="fa fa-envelope"></i> Sign up in our Newsletter</h3>
                <a href="#0" class="light-modal-close-icon" aria-label="close">&times;</a>
            </div>
            <!-- light modal body -->
            <div class="light-modal-body">
                <p>Subscribe to our weekly Newsletter and stay tuned.</p>
                <form action="." method="post">{% csrf_token %}
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                        {{ form }}
                    </div><br />
                    <button type="submit" value="sub" name="sub" class="btn btn-primary"><i class="fa fa-share"></i> Subscribe Now!</button>
                </form>
            </div>
            <!-- light modal footer -->
            <div class="light-modal-footer">
                <a href="#0" class="light-modal-close-btn" aria-label="close">Close</a>
            </div>
        </div>
    </div>

{% endblock content %}

src/templates/newsletters/sign_up_email.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Sign up newsletter</title>
</head>
<body>
	<h2>Welcom to BENZNANA'S site Newsletter</h2>
	<p>Thank you for joining</p>
	<p>To unsubscribe, visit this link: <a href='http://127.0.0.1:8000{% url "newsletters:newsletter_unsubscribe" %}'>Unsubscribe</a></p>
</body>
</html>

src/templates/newsletters/unsubscribe.html
{% extends "base.html" %}

{% block head_title %}
    Unsubscribe Newsletter | {{ block.super }}
{% endblock head_title %}

{% block content %}

<br>
<div class="container">
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="post">
                <div class="topwrap">
                    <div class="subscribe-section bg-with-black">
                        <div class="container">
                            <div class="row">
                                <div class="col-xs-12">
                                    <div class="subscribe-head">
                                        <h1>Newsletter</h1>
                                        <h2>You will be missed</h2>
                                        <p>We hate goodbyes-but if you have a change of heart, we'll always be here with great deals to share. Click bellow to unsubscribe...</p>
                                        <a href="#modal-id-2" class="btn"><i class="fa fa-sign-in" aria-hidden="true"></i>&nbsp;Unsubscribe</a>
                                        <small><em></em></small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="light-modal" id="modal-id-2" role="dialog" aria-labelledby="light-modal-label" aria-hidden="false">
    <div class="light-modal-content  animated zoomInUp">
        <!-- light modal header -->
        <div class="light-modal-header">
            <h3 class="light-modal-heading"><i class="fa fa-envelope"></i> Unsubscribe from our weekly Newsletter</h3>
            <a href="#0" class="light-modal-close-icon" aria-label="close">&times;</a>
        </div>
        <!-- light modal body -->
        <div class="light-modal-body">
            <p>Unsubscribe from our weekly Newsletter.</p>
            <form action="." method="post">{% csrf_token %}
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                    {{ form }}
                </div><br />
                <button type="submit" value="sub" name="sub" class="btn btn-primary"><i class="fa fa-share"></i> Unsubscribe</button>
            </form>
        </div>
        <!-- light modal footer -->
        <div class="light-modal-footer">
            <a href="#0" class="light-modal-close-btn" aria-label="close">Close</a>
        </div>
    </div>
</div>

{% endblock content %}

src/templates/newsletters/unsubscribe_email.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Unsubscribe newsletter</title>
</head>
<body>
	<h2>Sorry to see you go, let us know if there is an issue with our service</h2>
	<p>We try very hard to make BENZNANA'S Blog something great. Feedback from our users mean a lot to us.</p>
	<p>We'd love to know why you Unsubscribe.</p>
	<p>Bye Bye</p>
</body>
</html>