src/blog/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from accounts import views as account_views

from rest_framework_jwt.views import obtain_jwt_token

from accounts.views import (login_view, register_view, logout_view, change_password, create_profile)

from django.contrib.auth.views import (
    password_reset, 
    password_reset_done,
    password_reset_confirm, 
    password_reset_complete,
)

from posts.feeds import ArchiveFeed, AtomSiteNewsFeed

urlpatterns = [
    
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^admin/', admin.site.urls),
    url(r'^comments/', include("comments.urls", namespace='comments')),
    url(r'^profile/', account_views.profile, name='profile'),
    url(r'^register/', register_view, name='register'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^change-password/', change_password, name='change-password'),
    url(r'^create-profile/', create_profile, name='create_profile'),
    url(r'^', include("posts.urls", namespace='posts')),
    url(r'^api/posts/', include("posts.api.urls", namespace='posts-api')),
    url(r'^api/comments/', include("comments.api.urls", namespace='comments-api')),
    url(r'^api/users/', include("accounts.api.urls", namespace='users-api')),

    url(r'^newsletter/', include("newsletters.urls", namespace='newsletters')),

    url(r'^api/auth/token/', obtain_jwt_token),
    # url(r'^api/auth/token/', obtain_jwt_token),
    #url(r'^posts/$', "<appname>.views.<function_name>"),

    url(r'^account/reset-password/', password_reset,  name='reset_password'),
    url(r'^account/password-reset/done/$', password_reset_done, name='password_reset_done'),
    url(r'^account/password-reset/confirm/(?P<uidb64>[\w-]+)/(?P<token>[\w-]+)/$', password_reset_confirm, name='password_reset_confirm'),
    url(r'^account/password-reset/complete/$', password_reset_complete, name='password_reset_complete'),


    url(r'^oauth/', include("social_django.urls", namespace='social')),

    #url(r'^rss/', include("rss.urls", namespace='rss')),

    url(r'^feed/archive/$', ArchiveFeed(), name='archive-feed'),
    #url(r'^feed/atom/$', AtomSiteNewsFeed()),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/comments/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
    comment_thread,
    comment_delete

    )

urlpatterns = [
    url(r'^(?P<id>\d+)/$', comment_thread, name='thread'),
    url(r'^(?P<id>\d+)/delete/$', comment_delete, name='delete'),
]

src/posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	about,
	post_list,
	post_create,
	post_detail,
	post_update,
	post_delete,
	favourite_post,
	PostLikeToggle,
	PostLikeAPIToggle,
	PostnoLikeToggle,
	PostnoLikeAPIToggle,
	post_favourite_list,
	)

urlpatterns = [
	url(r'^$', post_list, name='list'),
	url(r'^about/$', about, name='about'),
    url(r'^create/$', post_create, name='create'),
    url(r'^(?P<id>\d+)/(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<id>\d+)/(?P<slug>[\w-]+)/like/$', PostLikeToggle.as_view(), name='like-toggle'),
    url(r'^api/(?P<id>\d+)/(?P<slug>[\w-]+)/like/$', PostLikeAPIToggle.as_view(), name='like-api-toggle'),
    url(r'^(?P<id>\d+)/(?P<slug>[\w-]+)/nolike/$', PostnoLikeToggle.as_view(), name='no-like-toggle'),
    url(r'^api/(?P<id>\d+)/(?P<slug>[\w-]+)/nolike/$', PostnoLikeAPIToggle.as_view(), name='no-like-api-toggle'),
    url(r'^(?P<id>\d+)/(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<id>\d+)/(?P<slug>[\w-]+)/delete/$', post_delete, name='delete'),
    url(r'^(?P<id>\d+)/(?P<slug>[\w-]+)/favourite_post/$', favourite_post, name='favourite_post'),
    url(r'^favourite/$', post_favourite_list, name='post_favourite_list'),
    #url(r'^posts/$', "<appname>.views.<function_name>"),
]

src/rss/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^feeds/', views.rest_feeds, name='rest-feeds'),
	url(r'^feeds/(?P<pk>[0-9]+)/$', views.rest_feeds_detail, name='rest-feeds-detail'),
	url(r'^items/', views.rest_items, name='rest-items')
]

src/comments/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db import models


class CommentManager(models.Manager):
    def all(self):
        qs = super(CommentManager, self).filter(parent=None)
        return qs

    def filter_by_instance(self, instance):
        content_type = ContentType.objects.get_for_model(instance.__class__)
        obj_id = instance.id
        qs = super(CommentManager, self).filter(content_type=content_type, object_id= obj_id).filter(parent=None)
        return qs

    def create_by_model_type(self, model_type, slug, content, user, parent_obj=None):
        model_qs = ContentType.objects.filter(model=model_type)
        if model_qs.exists():
            SomeModel = model_qs.first().model_class()
            obj_qs = SomeModel.objects.filter(slug=slug)
            if obj_qs.exists() and obj_qs.count() == 1:
                instance = self.model()
                instance.content = content
                instance.user = user
                instance.content_type = model_qs.first()
                instance.object_id = obj_qs.first().id
                if parent_obj:
                    instance.parent = parent_obj
                instance.save()
                return instance
        return None

class Comment(models.Model):
    user        = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    parent      = models.ForeignKey("self", null=True, blank=True)

    content     = models.TextField()
    timestamp   = models.DateTimeField(auto_now_add=True)

    objects = CommentManager()

    class Meta:
        ordering = ['-timestamp']


    def __unicode__(self):  
        return str(self.user.username)

    def __str__(self):
        return str(self.user.username)

    def get_absolute_url(self):
        return reverse("comments:thread", kwargs={"id": self.id})

    def get_delete_url(self):
        return reverse("comments:delete", kwargs={"id": self.id})
        
    def children(self): #replies
        return Comment.objects.filter(parent=self)

    @property
    def is_parent(self):
        if self.parent is not None:
            return False
        return True

src/comments/forms.py
from django import forms



class CommentForm(forms.Form):
    content_type = forms.CharField(widget=forms.HiddenInput)
    object_id = forms.IntegerField(widget=forms.HiddenInput)
    #parent_id = forms.IntegerField(widget=forms.HiddenInput, required=False)
    content = forms.CharField(label='', widget=forms.Textarea(attrs={'class':'form-control', 'placeholder': 'Write a comment...', 'rows': '2', 'cols': '50'}))

src/posts/forms.py
from django import forms

from pagedown.widgets import PagedownWidget

from django.utils.text import slugify

from .models import Post


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    #publish = forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            #"image",
            "draft",
            "publish",
            "restrict_comment",
        ]

        widgets = {'publish': forms.DateTimeInput(attrs={'class': 'date-input'})}

    def save(self):
        instance = super(PostForm, self).save(commit=False)
        instance.slug = slugify(instance.title)
        instance.save()

        return instance

src/comments/api/views.py
from django.db.models import Q
from rest_framework.filters import (
	SearchFilter,
	OrderingFilter
	)
from rest_framework.mixins import DestroyModelMixin, UpdateModelMixin
from rest_framework.generics import (
	CreateAPIView,
	ListAPIView, 
	RetrieveAPIView,
	UpdateAPIView,
	DestroyAPIView,
	RetrieveUpdateAPIView
	)
from rest_framework.permissions import (
	AllowAny,
	IsAuthenticated,
	IsAdminUser,
	IsAuthenticatedOrReadOnly
	)
from comments.models import Comment
from posts.api.pagination import PostLimitOffsetPagination, PostPageNumberPagination
from posts.api.permissions import IsOwnerOrReadOnly
from .serializers import (
	CommentListSerializer,
	CommentDetailSerializer,
	create_comment_serializer
	)


class CommentCreateAPIView(CreateAPIView):
	queryset = Comment.objects.all()
	#serializer_class = PostCreateUpdateSerializer
	#permission_classes = [IsAuthenticated]

	def get_serializer_class(self):
		model_type = self.request.GET.get("type")
		slug = self.request.GET.get("slug")
		parent_id = self.request.GET.get("parent_id", None)
		return create_comment_serializer(
				model_type=model_type,
				slug=slug,
				parent_id=parent_id,
				user=self.request.user
				)

	#def perform_create(self, serializer):
		#serializer.save(user=self.request.user)


class CommentDetailAPIView(DestroyModelMixin, UpdateModelMixin, RetrieveAPIView):
	queryset = Comment.objects.filter(id__gte=0)
	serializer_class = CommentDetailSerializer
	permission_classes = [IsOwnerOrReadOnly]

	def put(self, request, *args, **kwargs):
		return self.update(request, *args, **kwargs)

	def delete(self, request, *args, **kwargs):
		return self.destroy(request, *args, **kwargs)
		


# class PostUpdateAPIView(RetrieveUpdateAPIView):
# 	queryset = Post.objects.all()
# 	serializer_class = PostCreateUpdateSerializer
# 	lookup_field = 'slug'
# 	permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

# 	def perform_update(self, serializer):
# 		serializer.save(user=self.request.user)


# class PostDeleteAPIView(DestroyAPIView):
# 	queryset = Post.objects.all()
# 	serializer_class = PostDetailSerializer
# 	lookup_field = 'slug'
# 	permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]


class CommentListAPIView(ListAPIView):
	serializer_class = CommentListSerializer
	permission_classes = [AllowAny]
	filter_backends = [SearchFilter, OrderingFilter]
	search_fields = ['content', 'user__first_name']
	pagination_class = PostPageNumberPagination

	def get_queryset(self, *args, **kwargs):
		#queryset_list = super(PostListAPIView, self).get_queryset(*args, **kwargs)
		queryset_list = Comment.objects.filter(id__gte=0)
		query = self.request.GET.get("q")
		if query:
			queryset_list = queryset_list.filter(
					Q(content__icontains=query)|
					Q(user__first_name__icontains=query) |
					Q(user__last_name__icontains=query)
					).distinct()
		return queryset_list
		


		

src/comments/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseRedirect, Http404, HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404

from .forms import CommentForm
from .models import Comment

from django.template.loader import render_to_string



@login_required #(login_url='/login/') #LOGIN_URL = '/login/'
def comment_delete(request, id):
    #obj = get_object_or_404(Comment, id=id)
    # obj = CommentFormmment.objects.get(id=id)
    try:
        obj = Comment.objects.get(id=id)
    except:
        raise Http404

    if obj.user != request.user:
        #messages.success(request, "You do not have permission to view this.")
        #raise Http404
        reponse = HttpResponse("You do not have permission to do this.")
        reponse.status_code = 403
        return reponse
        #return render(request, "confirm_delete.html", context, status_code=403)

    parent_obj_url = obj.content_object.get_absolute_url()
    obj.delete()
    messages.success(request, "Comment has been successfully deleted.")
    return HttpResponseRedirect(parent_obj_url)


    # if request.method == "POST":
    #     parent_obj_url = obj.content_object.get_absolute_url()
    #     obj.delete()
    #     messages.success(request, "This has been deleted.")
    #     return HttpResponseRedirect(parent_obj_url)
    # context = {
    #     "object": obj
    # }
    # return render(request, "confirm_delete.html", context)

def comment_thread(request, id):
    #obj = Comment.objects.get(id=id)
    try:
        obj = Comment.objects.get(id=id)
    except:
        raise Http404

    if not obj.is_parent:
        obj = obj.parent

    content_object = obj.content_object # Post that the comment is on
    content_id = obj.content_object.id

    initial_data = {
            "content_type": obj.content_type,
            "object_id": obj.object_id
    }
    form = CommentForm(request.POST or None, initial=initial_data)
    if form.is_valid() and request.user.is_authenticated():
        c_type = form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model=c_type)
        obj_id = form.cleaned_data.get('object_id')
        content_data = form.cleaned_data.get("content")
        parent_obj = None
        try:
            parent_id = int(request.POST.get("parent_id"))
        except:
            parent_id = None

        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()


        new_comment, created = Comment.objects.get_or_create(
                            user = request.user,
                            content_type= content_type,
                            object_id = obj_id,
                            content = content_data,
                            parent = parent_obj,
                        )
        #return HttpResponseRedirect(new_comment.content_object.get_absolute_url())


    context = {
        "comment": obj,
        "form": form,
    }

    if request.is_ajax():
        html = render_to_string('comment_thread_serialized.html', context, request=request)
        return JsonResponse({'form': html})


    return render(request, "comment_thread.html", context)

src/posts/api/views.py
from django.db.models import Q

from rest_framework.filters import (
	SearchFilter,
	OrderingFilter
	)

from rest_framework.generics import (
	CreateAPIView,
	ListAPIView, 
	RetrieveAPIView,
	UpdateAPIView,
	DestroyAPIView,
	RetrieveUpdateAPIView
	)

from rest_framework.permissions import (
	AllowAny,
	IsAuthenticated,
	IsAdminUser,
	IsAuthenticatedOrReadOnly
	)

from posts.models import Post

from .pagination import PostLimitOffsetPagination, PostPageNumberPagination

from .permissions import IsOwnerOrReadOnly

from .serializers import (
	PostListSerializer, 
	PostDetailSerializer,
	PostCreateUpdateSerializer
	)



class PostListAPIView(ListAPIView):
	serializer_class = PostListSerializer
	filter_backends = [SearchFilter, OrderingFilter]
	search_fields = ['title', 'content', 'user__first_name']
	pagination_class = PostPageNumberPagination
	permission_classes = [AllowAny]


	def get_queryset(self, *args, **kwargs):
		#queryset_list = super(PostListAPIView, self).get_queryset(*args, **kwargs)
		queryset_list = Post.objects.all()
		query = self.request.GET.get("q")
		if query:
			queryset_list = queryset_list.filter(
					Q(title__icontains=query)|
					Q(content__icontains=query)|
					Q(user__first_name__icontains=query) |
					Q(user__last_name__icontains=query)
					).distinct()
		return queryset_list



class PostDetailAPIView(RetrieveAPIView):
	queryset = Post.objects.all()
	serializer_class = PostDetailSerializer
	lookup_field = 'slug'
	permission_classes = [AllowAny]


class PostCreateAPIView(CreateAPIView):
	queryset = Post.objects.all()
	serializer_class = PostCreateUpdateSerializer
	#permission_classes = [IsAuthenticated]

	def perform_create(self, serializer):
		serializer.save(user=self.request.user)


class PostUpdateAPIView(RetrieveUpdateAPIView):
	queryset = Post.objects.all()
	serializer_class = PostCreateUpdateSerializer
	lookup_field = 'slug'
	permission_classes = [IsOwnerOrReadOnly]

	def perform_update(self, serializer):
		serializer.save(user=self.request.user)


class PostDeleteAPIView(DestroyAPIView):
	queryset = Post.objects.all()
	serializer_class = PostDetailSerializer
	lookup_field = 'slug'
	permission_classes = [IsOwnerOrReadOnly]

src/templates/about.html
{% extends "base.html" %}
{% load staticfiles %}
{% load urlify %}
{% load crispy_forms_tags %}


{% block head_title %}
{{ title }} | {{ block.super }}
{% endblock head_title %}

{% block content %}



<div class="container">
    <div class="row">
        <div class="col-lg-8 breadcrumbf">
        	<a href="{% url 'posts:list' %}">Home</a> <span class="diviver">&gt;</span>
            {% block post_detail_link %}
                 <a href="{{ instance.get_absolute_url }}">{{ title }}</a>
            {% endblock %}
        </div>
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-8">
            <div class="post">
                <div class="topwrap">
                    <div class="posttext" style="padding: 30px;width: 100%">
                        <h3>Who we are ?</h3>
                        <p><img src="{% static 'images/car.jpg' %}" class="img-responsive" alt="" /></p>
                        <p>Today, we're looking at three particularly interesting stories. Pinterest added a new location-based feature on Wednesday that uses Place Pins as a way to map out vacations and favorite areas. Southwest Airlines is providing Wi-Fi access from gate to gate for $8 per day through an onboard hotspot. And in an effort to ramp up its user base, Google Wallet is offering a debit card that can take out cash from.</p>
                    </div>
                    <div class="clearfix"></div>
                </div>   
            </div>

        </div>
    </div>
</div>

{% endblock content %}

src/templates/change_password.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}
Reset Password | {{ block.super }}
{% endblock head_title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-12 col-md-12">
        	<div class="post" style="margin-top: 20px;">
        		<form method='POST' action='' class="form newtopic">{% csrf_token %}
                    <div class="postinfotop">
                        <h2>{{ title }}</h2>
                    </div>

                    <!-- acc section -->
                    <div class="accsection">
                        <div class="topwrap">
                            <div class="posttext pull-left" style="padding-left: 30px;width: 100%;">
                            	<div class="row">
                                    <div class="col-lg-12 col-md-12">
                                		{{ form|crispy }}
                                	</div>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                        </div>  
                    </div>
                    <div class="postinfobot">
                        <div class="pull-right postreply">
                            <div class="pull-left"><button type="submit" class="btn btn-primary">{{ title }}</button></div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </form>
            </div>
      	</div>
	</div>
</div>
{% endblock content %}

src/templates/comment_thread_serialized.html

<div class="container">
        <div class="row">
            <div class="col-lg-8 breadcrumbf">
                <a href="{% url 'posts:list' %}">Home</a> <span class="diviver">&gt;</span>
                <a href="{{ comment.content_object.get_absolute_url }}">{{ comment.content_object.title }}</a>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-white post panel-shadow">
                    <div class="post-heading">
                        <div class="pull-left image avatar">
                            <img src="{{ comment.user.profile.image.url }}" class="img-circle avatar" alt="user profile image" />
                            {% if comment.user == request.user %}
                                <div class="status green">&nbsp;</div>
                            {% endif %}
                        </div>
                        <div class="pull-left meta">
                            <div class="title h5">
                                <a href="#0"><b>
                                  {% if comment.user.get_full_name %}
                                    {{ comment.user.get_full_name }}
                                  {% else %} 
                                    {{ comment.user.username }}
                                  {% endif %}
                                </b></a>
                                made a comment.
                            </div>
                            <h6 class="text-muted time_post">{{ comment.timestamp|timesince }} ago </h6>
                        </div>
                        {% if request.user == comment.user %}
                          <div class="pull-right">
                            <div class="dropdown">
                                <button class="btn btn-link dropdown-toggle" type="button" id="dropdownMenuAction" data-toggle="dropdown" title="Remove this">
                                    <i class="fa fa-ellipsis-h"></i>
                                </button>
                                <ul class="dropdown-menu dropdown-menu-right dropdownMenuAction" role="menu" aria-labelledby="dropdownMenuAction">
                                    <li role="presentation">
                                        <a role="menuitem" tabindex="-1" id="pb-confirm-delete-comment" title="Remove comment">
                                            <i class="fa fa-trash-o" aria-hidden="true"></i> Delete...
                                        </a>
                                          <script type="text/javascript">
                                            document.getElementById('pb-confirm-delete-comment').onclick = function () {
                                              pb.confirm(
                                                function (outcome) {
                                                    if(outcome){
                                                        window.location.href = "{{ comment.get_delete_url }}";
                                                        return true;
                                                    }else{
                                                        return false;
                                                    }
                                                },
                                                'Are you sure you want to delete this comment ?',
                                                'Yes',
                                                'No'
                                              );
                                            }
                                        </script>
                                    </li>
                                    <!--<li role="presentation" class="divider"></li>-->
                                </ul>
                            </div>
                          </div>
                        {% endif %}
                    </div> 
                    <div class="post-description"> 
                        <p>{{ comment.content }}</p>
                        <div class="stats">
                            <a href="#0" class="btn btn-default stat-item">
                                <i class="fa fa-share icon"></i>
                                {% if comment.children.count > 0 %}
                                  {{ comment.children.count }} Repl{% if comment.children.count > 1 %}ies{% else %}y{% endif %}
                                {% endif %}
                            </a>
                        </div>
                    </div>
                    <div class="post-footer">
                        {% if request.user.is_authenticated %}
                          <form method="POST" action="." class="thread-form"> {% csrf_token %}
                            <div class="input-group"> 
                                {{ form }}
                                <span class="input-group-addon">
                                    <input type='hidden' name='parent_id' value='{{ comment.id }}'>
                                    <button type="submit"><i class="fa fa-edit"></i></button>
                                </span>
                            </div>
                          </form>
                        {% endif %}
                        <ul class="comments-list-thread">
                          {% for child_comment in comment.children %}
                            <li class="comment">
                                <div class="pull-left avatar">
                                    <img class="avatar" src="{{ child_comment.user.profile.image.url }}" alt="avatar">
                                    {% if child_comment.user == request.user %}
                                        <div class="status green">&nbsp;</div>
                                    {% endif %}
                                </div>
                                <div class="comment-body">
                                    <div class="comment-heading">
                                        <h4 class="user">
                                          {% if child_comment.user.get_full_name %}
                                            {{ child_comment.user.get_full_name }}
                                          {% else %} 
                                            {{ child_comment.user.username }}
                                          {% endif %}
                                        </h4>
                                        <h5 class="time_post">{{ child_comment.timestamp|timesince }} ago</h5>
                                        {% if request.user == child_comment.user %}
                                          <div class="pull-right">
                                              <a class='btn btn-danger ask' title="Remove comment" href='{{ child_comment.get_delete_url }}'>
                                                <i class="fa fa-times" aria-hidden="true"></i>
                                              </a>
                                          </div>
                                        {% endif %}
                                    </div>
                                    <p>{{ child_comment.content }}</p>
                                </div>
                            </li>
                          {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

src/templates/profile.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}


{% block head_title %}
{{ title }} | {{ block.super }}
{% endblock head_title %}

{% block content %}


	<div class="container">
        <div class="row">
            <div class="col-md-12 breadcrumbf">
                <a href="{% url 'posts:list' %}">Home</a> <span class="diviver">&gt;</span>
                {% block post_detail_link %}
                     <a href="{{ instance.get_absolute_url }}">{{ title }}</a>
                {% endblock %}
            </div>
        </div>
    </div>


    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <!-- POST -->
                <div class="post">
                    <form class="form newtopic" method="post" enctype="multipart/form-data">{% csrf_token %}
                        <div class="postinfotop">
                            <h2>Profile Info</h2>
                        </div>

                       <div class="panel panel-default">
                           <div class="panel-heading resume-heading">
                              <div class="row">
                                 <div class="col-lg-12">
                                    <div class="col-xs-12 col-sm-4">
                                       <figure>
                                          <img class="img-responsive" alt="{{ user.username }}" src="{{ user.profile.image.url }}" width="100%">
                                       </figure>
                                       <ul class="list-group">
                                          <li class="list-group-item">
                                            {% if user.get_full_name %}
                                                {{ user.get_full_name }}
                                            {% else %}
                                                {{ user.username }}
                                            {% endif %}
                                          </li>
                                          <li class="list-group-item"><a href="mailto:{{ user.email }}" title="Send email">
                                            <i class="fa fa-envelope"></i> {{ user.email }}</a>
                                          </li>
                                       </ul>
                                    </div>
                                    <div class="col-xs-12 col-sm-8">
                                        <div class="content-section" style="padding: 15px 45px 10px 45px;background-color: #fff;">
                                            <fieldset class="form-group">
                                                {{ u_form|crispy }}
                                                {{ p_form|crispy }}
                                            </fieldset>
                                        </div>
                                        <div class="pull-right postreply">
                                            <button type="submit" class="btn btn-primary">Update</button>
                                            <div class="clearfix"></div>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                    </form>
                </div>
			</div>
		</div>
	</div>


{% endblock content %}